version: 0.0
os: linux
files:
  - source: /
    destination: /home/ubuntu/app
    overwrite: true  # ✅ Ensure files get overwritten

hooks:
  ApplicationStop:
    - location: scripts/stop_server.sh
      timeout: 300
      runas: ubuntu
  BeforeInstall:
    - location: scripts/clean_old_files.sh  # ✅ Add cleanup script before install
      timeout: 300
      runas: ubuntu
  AfterInstall:
    - location: scripts/install_dependencies.sh
      timeout: 300
      runas: ubuntu
  ApplicationStart:
    - location: scripts/start_server.sh
      timeout: 300
      runas: ubuntu
