version: 0.0
os: linux
files:
  - source: /  # Copy all files from the deployment package
    destination: /home/ubuntu/app  # Destination directory on the EC2 instance
hooks:
  ApplicationStop:
    - location: scripts/stop_server.sh
      timeout: 300
      runas: ubuntu
  BeforeInstall:
    - location: scripts/install_dependencies.sh
      timeout: 300
      runas: ubuntu
  AfterInstall:
    - location: scripts/start_server.sh
      timeout: 300
      runas: ubuntu
