name: Build & Deploy to CI-ASG

on:
  push:
    branches: [ "master" ]
  workflow_dispatch:  # Enable manual triggers

env:
  AWS_REGION: ap-south-1
  S3_BUCKET: java-space
  CODE_DEPLOY_APP: CICD
  DEPLOYMENT_GROUP: DEV-CICD

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read

    steps:
      # 1. Checkout code
      - uses: actions/checkout@v4

      # 2. Setup Node.js (match your runtime)
      - uses: actions/setup-node@v4
        with:
          node-version: '20.x'
          cache: 'npm'

      # 3. Install & Build
      - name: Install dependencies
        run: npm ci --omit=dev

      - name: Run tests
        run: npm test

      - name: Build production
        run: npm run build

      # 4. Prepare deployment package
      - name: Create deployment bundle
        run: |
          # Include only essential files
          mkdir -p dist
          cp -r build package.json package-lock.json appspec.yml scripts dist/
          
          # Generate unique version ID
          TIMESTAMP=$(date +%Y%m%d%H%M%S)
          GIT_SHA=$(git rev-parse --short HEAD)
          ZIP_NAME="deploy-${TIMESTAMP}-${GIT_SHA}.zip"
          
          cd dist && zip -r ../${ZIP_NAME} .
          echo "ZIP_NAME=${ZIP_NAME}" >> $GITHUB_ENV

      # 5. Configure AWS credentials
      - uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::120569639058:role/github-actions-role
          aws-region: ${{ env.AWS_REGION }}

      # 6. Upload to S3
      - name: Upload deployment package
        run: |
          aws s3 cp ${ZIP_NAME} s3://${{ env.S3_BUCKET }}/build/${ZIP_NAME}

      # 7. Trigger CodeDeploy (matches your HalfAtATime config)
      - name: Deploy to CI-ASG
        run: |
          aws deploy create-deployment \
            --application-name ${{ env.CODE_DEPLOY_APP }} \
            --deployment-group-name ${{ env.DEPLOYMENT_GROUP }} \
            --s3-location bucket=${{ env.S3_BUCKET }},key=build/${ZIP_NAME},bundleType=zip \
            --description "Deploying ${ZIP_NAME} to CI-ASG"
