name: CI - Build and Upload to CodePipeline S3

on:
  push:
    branches: [ "master" ]
  workflow_dispatch:

env:
  AWS_REGION: ap-south-1
  S3_BUCKET: codepipeline-ap-south-1-637572467395

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '21.x'
          cache: 'npm'

      - name: Install dependencies
        run: npm ci --omit=dev

      - name: Run tests (if defined)
        run: |
          if grep -q '"test"' package.json; then
            npm test
          else
            echo "No tests defined"
          fi

      - name: Build project
        run: npm run build

      - name: Create ZIP of build
        run: |
          TIMESTAMP=$(date +%Y%m%d%H%M%S)
          GIT_SHA=$(git rev-parse --short HEAD)
          ZIP_NAME="app-${TIMESTAMP}-${GIT_SHA}.zip"
          zip -r $ZIP_NAME build/
          echo "ZIP_NAME=$ZIP_NAME" >> $GITHUB_ENV

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::<YOUR_ACCOUNT_ID>:role/github-actions-role  # Replace with your IAM Role ARN
          aws-region: ${{ env.AWS_REGION }}

      - name: Upload ZIP to S3 (for CodePipeline)
        run: |
          aws s3 cp $ZIP_NAME s3://${{ env.S3_BUCKET }}/$ZIP_NAME
