name: Build & Deploy to AWS

on:
  push:
    branches: [ "master" ]

permissions:
  id-token: write   # Required for OIDC
  contents: read    # Required to checkout code

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # 1. Checkout code
      - name: Checkout
        uses: actions/checkout@v4

      # 2. Configure AWS credentials via OIDC
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::120569639058:role/github-actions-role
          aws-region: ap-south-1

      # 3. Install dependencies (Node.js example)
      - name: Install Dependencies
        run: npm install

      # 4. Build the application
      - name: Build
        run: npm run build

      # 5. Create deployment package (exclude unnecessary files)
      - name: Create ZIP Artifact
        run: |
          zip -r app.zip . -x "node_modules/*" ".git/*" ".github/*" "*.md"
          echo "DEPLOYMENT_VERSION=$(date +%Y%m%d%H%M%S)" >> $GITHUB_ENV

      # 6. Upload to S3
      - name: Upload to S3
        run: |
          aws s3 cp app.zip s3://java-space/build/app-$DEPLOYMENT_VERSION.zip

      # 7. Trigger CodeDeploy
      - name: Deploy to EC2 via CodeDeploy
        run: |
          aws deploy create-deployment \
            --application-name CICD \
            --deployment-group-name DEV-CICD \
            --s3-location bucket=java-space,key=build/app-$DEPLOYMENT_VERSION.zip,bundleType=zip
