name: Build & Deploy to CI-ASG

on:
  push:
    branches: [ "master" ]
  workflow_dispatch:

env:
  AWS_REGION: ap-south-1
  S3_BUCKET: java-space
  CODE_DEPLOY_APP: CICD
  DEPLOYMENT_GROUP: DEV-CICD

jobs:
  build:
    runs-on: ubuntu-latest
    outputs:
      zip_name: ${{ steps.package.outputs.zip_name }}
    
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: '21.x'
          cache: 'npm'

      - name: Install dependencies
        run: npm ci --omit=dev

      # Only run tests if they exist
      - name: Run tests (if any)
        run: |
          if grep -q '"test"' package.json; then
            npm test
          else
            echo "No tests defined in package.json"
          fi

      - name: Build production
        run: npm run build

      - name: Create deployment package
        id: package
        run: |
          mkdir -p dist
          cp -r build package.json package-lock.json appspec.yml scripts dist/
          
          TIMESTAMP=$(date +%Y%m%d%H%M%S)
          GIT_SHA=$(git rev-parse --short HEAD)
          ZIP_NAME="deploy-${TIMESTAMP}-${GIT_SHA}.zip"
          
          cd dist && zip -r ../${ZIP_NAME} .
          echo "zip_name=${ZIP_NAME}" >> $GITHUB_OUTPUT

      - name: Upload artifact (for debugging)
        uses: actions/upload-artifact@v4
        with:
          name: deployment-package
          path: ${{ steps.package.outputs.zip_name }}

  deploy:
    needs: build
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read

    steps:
      - uses: actions/download-artifact@v4
        with:
          name: deployment-package

      - uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::120569639058:role/github-actions-role
          aws-region: ${{ env.AWS_REGION }}

      - name: Upload to S3
        run: |
          aws s3 cp ${{ needs.build.outputs.zip_name }} s3://${{ env.S3_BUCKET }}/build/${{ needs.build.outputs.zip_name }}

      - name: Trigger CodeDeploy
        run: |
          aws deploy create-deployment \
            --application-name ${{ env.CODE_DEPLOY_APP }} \
            --deployment-group-name ${{ env.DEPLOYMENT_GROUP }} \
            --s3-location bucket=${{ env.S3_BUCKET }},key=build/${{ needs.build.outputs.zip_name }},bundleType=zip \
            --description "Deploying ${{ needs.build.outputs.zip_name }}"
